FROM node:20-alpine

WORKDIR /app

COPY . .
RUN npm install

WORKDIR /app/apps/api
RUN npx prisma generate

EXPOSE 3000

CMD ["sh", "-c", "npx prisma db push --skip-generate --accept-data-loss && npm run seed && npm run start:dev"]
